No multiarch out of tree
sailfishos/scratchbox2 pull request #32
Opened 2024-03-29 03:09 UTC by Thaodan

Cleans up the makefile a bit and remove the builtin multilib variant that wasn't used:

Contains changes from #22 and #23.

2025-01-13 13:01 UTC, martyone commented on utils/sb2-session
> +		if [ -e $s ] ; then
I would prefer doing `[ -e $s ] || continue` instead.

2025-01-13 13:01 UTC, martyone commented on utils/sb2
> +			  cpio -pamd $SBOX_SESSION_DIR/target_root) ; then
While touching these it would be nice to fix it to have operators (`|`, `||`, `&&` etc.) at the beginnings of continuation lines.

```suggestion
	if ! (cd $source_directory; find . -depth -print \
			| cpio -pamd $SBOX_SESSION_DIR/target_root) ; then
```

2025-01-13 13:01 UTC, martyone commented on utils/sb2-session
>  			echo "sb2 session"
I'd suggest to pass the message directly and replace also the second `echo`. More occurrences elsewhere.

2025-01-13 13:01 UTC, martyone commented on utils/sb2-session
>  		fi
I think this does not work as expected. First, `-printf` would have to be used or `x` is treated as a path. Second, it also prints the `env_vars` dir itself. Also maybe replace the whole thing with

```
		find "$SBOX_SESSION_DIR/env_vars" -type f -exec cat '{}' ';'
```

2025-01-13 13:01 UTC, martyone commented on utils/sb2-upgrade-config
> +			$compiler_path; then
I am not sure about these. Unless indented once more, readability is worse then with the original.

2025-01-13 13:01 UTC, martyone commented on utils/sb2
> +		exit_error "Configure mode doesn't '$SBOX_MAPMODE' for target doesn't exist, aborting."
Typo?

2025-01-13 13:01 UTC, martyone commented on utils/sb2-config-gcc-toolchain.sh.in
> +    -S SBOX_DATADIR       define value for SBOX_DIR
Bad spacing?

2025-01-13 13:01 UTC, martyone commented on utils/sb2-config-gcc-toolchain.sh.in
> +    SBOX_DATADIR=@datadir@
Bad indent?

2025-01-13 13:01 UTC, martyone commented on utils/sb2-init.sh.in
> +if [ -z "$SBOXDATA_DIR" ]; then
typo? SBOX_DATADIR. Similar below.

2025-01-13 13:01 UTC, martyone commented on utils/sb2.sh.in
> +	printf "$ld_so_conf"
Using spaces for indentation by mistake? More occurrences elsewhere.

2025-01-13 13:01 UTC, martyone commented on utils/sb2.sh.in
> +    done
Bad indent. Consider using `[ -d $rootdir$liblocation ] || continue` to avoid extra nesting.

2025-01-13 13:01 UTC, martyone commented on utils/sb2.sh.in
> +    done
Bad indent. More occurrences elsewhere.

2025-01-13 13:01 UTC, martyone commented on utils/sb2.sh.in
> +                    if [ -e $wrapper ]; then
I'd prefer `foo || continue`. More occurrences below.

2025-01-13 13:01 UTC, martyone commented on configure.ac
> +        [bjorn.bidar@jolla.com],
https://forum.sailfishos.org/ could be more appropriate for bug reporting or maybe leave empty?

2025-01-13 13:01 UTC, martyone commented on .gitignore
> +stamp-h.in
Are the `.in` files actually used?

2025-01-13 13:01 UTC, martyone commented on Makefile
> +# files such as configure.ac e.g. after checking out a new branch
Are you sure this is not going to be a kind of gotcha after all? Is it still easier and more transparent than the original approach before "Use autotools builtin system to rerun configure instead of our own"? (I haven't checked thoroughly.)

2025-01-14 00:00 UTC, Thaodan commented on Makefile
> +# files such as configure.ac e.g. after checking out a new branch
The old system did not take care of rebuilding autoconf at all besides creating if it didn't exist.

Using config.status is the intended way of regenerating the build system. The issue lies with the timestamps not updating when the result of configure.ac or config.h.in did not change but the timestamp of the source flie did (e.g. configure.ac did).

Using the timestamp files ensures that configure is regenerated if configure.ac changed once and not every time make is invoked since configure.ac  will be newer if e.g. git changes it's timestamp or other changes to the file such as comments where added which do not change it's output file.

The same applies to config.h of course.

2025-01-14 00:01 UTC, Thaodan commented on configure.ac
> +        [bjorn.bidar@jolla.com],
I will check.

2025-01-14 00:08 UTC, Thaodan commented on utils/sb2-session
>  		fi
Why cat? That would open each file. I will change to printf and match only files.

2025-01-14 00:09 UTC, Thaodan commented on .gitignore
> +stamp-h.in
Yes  they are later down the line by configure.

2025-01-14 07:05 UTC, martyone commented on utils/sb2-session
>  		fi
I think you misread something. Or if your concerns are about forking `cat` for each file, then of course, we can optimize with `find ...|xargs cat` :)

2025-01-14 07:05 UTC, martyone commented on .gitignore
> +stamp-h.in
Ah now I see how.

2025-01-14 07:05 UTC, martyone commented on Makefile
> +# files such as configure.ac e.g. after checking out a new branch
OK, consider adding "See Automatic Remaking in autoconf's manual" to the comment. The link did not open.

2025-01-14 09:29 UTC, Thaodan commented on utils/sb2-session
>  		fi
My concerns are about opening each file with cat when the point of this command is only to  count amount of files.

2025-01-14 09:34 UTC, Thaodan commented on Makefile
> +# files such as configure.ac e.g. after checking out a new branch
Oh I see it that now. I seems that info gave me the wrong link to the HTML version of the manual.

Here is the right link:
https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.72/html_node/Automatic-Remaking.html

2025-01-14 10:22 UTC, martyone commented on utils/sb2-session
>  		fi
Check it again :) If the count is greater than zero, then all files are `cat` to the stdout. Hence the command I suggested, which does it all in one "step".

2025-01-14 10:28 UTC, martyone commented on Makefile
> +# files such as configure.ac e.g. after checking out a new branch
Yup, I was able to quickly find it. I just meant it would be good to refer it in the comment and maybe use natural language instead of the version-specific URL.

2025-01-23 17:49 UTC, Thaodan commented on utils/sb2-session
>  		fi
Ah I get it now. Thanks.

2025-01-23 18:11 UTC, Thaodan commented on utils/sb2-upgrade-config
> +			$compiler_path; then
Because of the deeper nesting?

2025-01-29 06:00 UTC, Thaodan commented on configure.ac
> +        [bjorn.bidar@jolla.com],
Changed to  a link to Sailfish Docs.

2025-01-29 08:28 UTC, direc85 commented on Makefile
> +	$(Q)install -m 755 $(OBJDIR)/utils/sb2-config-gcc-toolchain $(DESTDIR)$(datadir)/scratchbox2/scripts/sb2-config-gcc-toolchain
I would group the install lines in these blocks by `$(OBJDIR)` and `$(SRCDIR)` to highlight the difference.

2025-01-29 08:36 UTC, direc85 commented on utils/sb2-session
> +    attach|save|delete|setenv|showenv)
`save` command can only be run from inside sb2 session.

2025-01-29 16:53 UTC, mlehtima commented on rpm/scratchbox2.spec
>  ExclusiveArch:	%{ix86} %{x86_64}
Fix this while at it, x86_64 macro is only available in rpm 4.19 or newer. So replace %{x86_64} with x86_64 for now.

2025-01-29 18:33 UTC, Thaodan commented on Makefile
> +	$(Q)install -m 755 $(OBJDIR)/utils/sb2-config-gcc-toolchain $(DESTDIR)$(datadir)/scratchbox2/scripts/sb2-config-gcc-toolchain
Currently they are grouped by subfolders. What do you think is better?

2025-01-29 20:59 UTC, direc85 requested changes, later dismissed

2025-01-29 20:59 UTC, direc85 commented on rpm/scratchbox2.spec
> +ExclusiveArch:	%{ix86} %{x86_64} x86_64
Both %{x86_64} and x86_64 here now?

2025-01-29 20:59 UTC, direc85 commented on Makefile
> +	$(Q)install -m 755 $(OBJDIR)/utils/sb2-config-gcc-toolchain $(DESTDIR)$(datadir)/scratchbox2/scripts/sb2-config-gcc-toolchain
Either works, this is a nitpick anyway :)

2025-01-29 20:59 UTC, direc85 commented on utils/sb2-session
> +							 sed 's/SBOX_SESSION_DESCRIPTION="\([^"]*\)"/\1/' )
Weird intent? Spaces vs. tabs I think?

2025-01-29 21:22 UTC, Thaodan commented on rpm/scratchbox2.spec
> +ExclusiveArch:	%{ix86} %{x86_64} x86_64
Either %{x86_64} is expanded or empty. Either way x86_64 works as a fallback.

2025-02-05 13:04 UTC, direc85 commented on Makefile
> +all: $(DIST_FILES) $(OBJDIR)/include/config.h .WAIT do-all
Since `.WAIT` [requires make 4.4](https://lwn.net/Articles/913253/), would this work instead?
```suggestion
all: $(DIST_FILES) $(OBJDIR)/include/config.h do-all
.NOTPARALLEL: all
```

2025-02-05 13:12 UTC, direc85 commented on Makefile
> +all: $(DIST_FILES) $(OBJDIR)/include/config.h .WAIT do-all
Or make could be told that there's a dependency, something like this?

```suggestion
all: do-first do-all
do-first: $(DIST_FILES) $(OBJDIR)/include/config.h
do-all: do-first $(targets)
```

2025-02-05 23:01 UTC, direc85 commented
6c5679af49a0da9959e0620468381bbd0879855b doesn't compile on Patform SDK:
```text
/srv/mer/toolings/SailfishOS-devel/opt/cross/bin/i486-meego-linux-gnu-ld:/home/mattiv/PSDK/scratchbox2/build/preload/export.map: file format not recognized; treating as linker script
/srv/mer/toolings/SailfishOS-devel/opt/cross/bin/i486-meego-linux-gnu-ld:/home/mattiv/PSDK/scratchbox2/build/preload/export.map:1: syntax error
collect2: error: ld returned 1 exit status
```

2025-02-06 07:39 UTC, Thaodan commented
> [6c5679a](https://github.com/sailfishos/scratchbox2/commit/6c5679af49a0da9959e0620468381bbd0879855b) doesn't compile on Patform SDK:
> 
> ```
> /srv/mer/toolings/SailfishOS-devel/opt/cross/bin/i486-meego-linux-gnu-ld:/home/mattiv/PSDK/scratchbox2/build/preload/export.map: file format not recognized; treating as linker script
> /srv/mer/toolings/SailfishOS-devel/opt/cross/bin/i486-meego-linux-gnu-ld:/home/mattiv/PSDK/scratchbox2/build/preload/export.map:1: syntax error
> collect2: error: ld returned 1 exit status
> ```

That's fixed now.

2025-02-06 14:07 UTC, martyone reviewed
Noticed just some stylish issues.

In addition to those, it would really be nice, now that we are touching all the multi-line expressions, to ensure operators are at the beginnings of the continuation lines and not hanging at the ends.

I am not 100% sure readability improves by eliminating the indirect checks of exit codes `[ $? -eq 0 ]`. At least I would ensure that the continuation lines of a multi-line `if` conditions use two levels of indentation, so that it is immediately clear where the body starts. With that, we do not need to break the convention if placing the `then` keyword at the end of the line.

```
if my super long \
        command as a condition \
        && another one \
            |further filtered \
        || alternatively this one; then
    the body starts here
    and continues
fi
```

2025-02-06 14:07 UTC, martyone commented on utils/sb2
> +            if ! $SBOX_DIR/share/scratchbox2/scripts/sb2-upgrade-config $SBOX_TARGET; then
Bad indent

2025-02-06 14:07 UTC, martyone commented on utils/sb2
> +        if ! SBOX_SESSION_DIR=$(mktemp -d /tmp/sb2-$USER-$date_and_time_now.XXXXXX) ; then
Bad indent

2025-02-06 14:07 UTC, martyone commented on utils/sb2-config
> +	    count=$(find "$SBOX_SESSION_DIR/env_vars" -print x | wc -c )
Bad indent

2025-02-06 14:07 UTC, martyone commented on utils/sb2-exitreport
> +	   [ -z "$exit_reason" ] || [ -z "$exit_status" ]; then
Bad indent

2025-02-06 14:07 UTC, martyone commented on utils/sb2.sh.in
> +		for wrapper in $SBOX_DATADIR/ ; do
Feels like something is missing here.

2025-02-06 14:07 UTC, martyone commented on utils/sb2.sh.in
> +				       ; do
Typo?

2025-02-06 14:07 UTC, martyone commented on utils/sb2.sh.in
> +		    if [ $wrapper_found = nil ] ; then
I would prefer simply using empty value as False and 1 as True.
```
wrapper_found=
if ...
    wrapped_found=1
fi
if [ ! $wrapper_found ]; then
...
```

2025-02-06 14:07 UTC, martyone commented on utils/sb2.sh.in
> +			wrapper_found=wrapper_found=t
Typo?

2025-02-06 14:07 UTC, martyone commented on rpm/scratchbox2.spec
> +# Note we don't strip the version here not to not remove the indicator
Extra not

2025-02-06 14:07 UTC, martyone commented on Makefile
> +# Read "(autoconf) Automatic Remaking" in Info or follow:x
Typo?

2025-02-06 14:07 UTC, martyone commented on utils/sb2-session
> +			|| die die "'save' command can only be run from inside sb2 session"
Afraid it could return? :)

2025-02-06 16:19 UTC, Thaodan commented on utils/sb2-session
> +			|| die die "'save' command can only be run from inside sb2 session"
Just to be sure it's dead.

2026-01-14 14:30 UTC, pvuorela commented on rpm/scratchbox2.spec
>  URL:		https://git.sailfishos.org/mer-core/scratchbox2
Hey btw this could be fixed in whatever PR that's getting first in. One rare remaining case of mer-core.

2026-08-28 15:06 UTC, direc85 approved these changes

2026-08-28 15:53 UTC, merged